# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/LaTeX.gitlab-ci.yml

---
variables:
  LATEX_IMAGE: listx/texlive:2020

build:
  image: $LATEX_IMAGE
  script: 
    - latexmk -pdf resume.tex
  artifacts:
    paths:
      - resume.pdf
    expire_in: 1 week
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'

release:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - echo "Creating release"
  release:
    name: 'Release $CI_COMMIT_TAG'
    description: 'updated resume'
    tag_name: 'release-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA'
    ref: '$CI_COMMIT_SHA'