# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/LaTeX.gitlab-ci.yml

---
variables:
  LATEX_IMAGE: listx/texlive:2020

build:
  image: $LATEX_IMAGE
  script: 
    - latexmk -pdf resume.tex
  artifacts:
    paths:
      - resume.pdf
    expire_in: 1 week
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'

release:
  stage: deploy
  image: gcc:latest
  script: 
   script:
    - apt-get update && apt-get install -y jq
    - RELEASE_NAME="Release $(date +'%Y-%m-%d %H:%M:%S')"
    - RELEASE_DESCRIPTION="Release for commit $CI_COMMIT_SHORT_SHA"
    - >
      curl --header 'Content-Type: application/json' --header "JOB-TOKEN: $CI_JOB_TOKEN" 
      --data '{
        "name": "'"$RELEASE_NAME"'",
        "tag_name": "'"$CI_COMMIT_REF_NAME"'",
        "description": "'"$RELEASE_DESCRIPTION"'",
        "assets": {
          "links": [{
            "name": "a.out",
            "url": "'"$CI_PROJECT_URL"/-/jobs/$CI_JOB_ID/artifacts/a.out",
            "filepath": "/a.out",
            "link_type": "other"
          }]
        }
      }'
      "$CI_API_V4_URL/projects/$CI_PROJECT_ID/releases"